# Generated by Django 3.2 on 2022-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data_added',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
