# Generated by Django 3.2 on 2022-07-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_data_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='data_added',
        ),
    ]
