# Generated by Django 3.2 on 2022-07-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20220721_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('literature', '文芸'), ('hobby', '趣味実用'), ('business', 'ビジネス'), ('life', '生活'), ('trip', '旅行'), ('general_education', '一般教養'), ('self_enlightenment', '自己啓発'), ('children', '子供'), ('other', 'その他')], max_length=100),
        ),
    ]
